version: '3'
services:
    web:
        container_name: mkpc_web
        build:
            context: ./docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - ./docker/php/images/avatars:/var/www/html/images/avatars
            - ./docker/php/images/uploads:/var/www/html/images/uploads
            - ./docker/php/images/sprites/uploads:/var/www/html/images/sprites/uploads
            - ./docker/php/images/creation_icons:/var/www/html/images/creation_icons
            - ./docker/php/config:/var/www/html/config
            - ./docker/php/scripts:/root/scripts
        ports:
            - "8080:80"
    app:
        container_name: mkpc_app
        build:
            context: ./v2/app
        depends_on:
            - node-api
        volumes:
            - ./v2/app:/app
    node-api:
        container_name: mkpc_node
        build:
            context: ./v2/node-api
        depends_on:
            - web
        volumes:
            - ./v2/node-api:/usr/src/app
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'mkpc'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'mkpc_user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'mkpc_pwd'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '8306:3306'
        expose:
            - '3306'
        volumes:
            - mkpc-db:/var/lib/mysql
volumes:
    mkpc-db: