version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        depends_on:
            - db
        volumes: 
            - .:/var/www/html
            - /var/www/html/images/avatars/
            - /var/www/html/images/sprites/uploads/
            - /var/www/html/images/creation_icons/
            - ./docker/php/test:/var/www/html/test
        ports:
            - "8080:80"
    db:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        restart: 'always'
        ports:
            - "3307:3306"